### PR TITLE
feat: Cookbook Onboard integration (AI Assistant)

### PR DESCRIPTION
**Pull request by ClockRide**
The AI assistant and co-pilot is trained on all existing Flare resources (source code, docs website, etc) and is available as a standalone modal, embeddable as a button on any page (recommended for technical docs). It answers developer questions about building projects on Flare, acting as an enhanced and streamlined technical documentation search tool as well as a Solidity coding co-pilot.

Ask Cookbook AI could also access context from thousands of data sources indexed by Cookbook.dev in addition to Flare-specific data sources, providing the best blockchain developer-focused answers of any chatbot on the market. Cookbook will assist in the tuning and calibration of the AI assistant to ensure the highest answer quality.

## Preview
https://docsbot-demo-git-flare-cookbookdev.vercel.app/

image

### CODE REVIEW

**Comment by ClockRide** [comment]
@segfaultxavi, could you please review this when you have a chance?

**Comment by segfaultxavi** [comment]
@dineshpinto can take care of this, I believe.

**Comment by dineshpinto** [comment]
Hi @ClockRide, this is an interesting idea and there is value in it. However, the information currently provided by this AI assistant is incorrect in several places and may mislead developers and users on Flare (it even suggested running a full node when asked about deploying a contract). Closing this PR.

**Comment by whatupjeff** [comment]
@dineshpinto Can you share some examples of some of these incorrect chats?

**Pull request closed without merging**
